# Generated by Django 4.2.13 on 2024-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionInfo',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RoleInfo',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=16)),
                ('functions', models.ManyToManyField(to='app.functioninfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('identity', models.CharField(max_length=16)),
                ('email', models.CharField(blank=True, max_length=16, null=True)),
                ('roles', models.ManyToManyField(to='app.roleinfo')),
            ],
        ),
    ]
