# Generated by Django 4.2.13 on 2024-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excess_Return_All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf', models.CharField(max_length=100)),
                ('Index_ExRet', models.CharField(max_length=100)),
                ('Min_Var_Excess_Returns', models.CharField(max_length=100)),
                ('Util_Max_Excess_Returns', models.CharField(max_length=100)),
                ('Equal_Excess_Returns', models.CharField(max_length=100)),
                ('Cumulative_Index_ExRet', models.CharField(max_length=100)),
                ('Cumulative_Min_Var_ExRet', models.CharField(max_length=100)),
                ('Cumulative_Util_Max_ExRet', models.CharField(max_length=100)),
                ('Cumulative_equal', models.CharField(max_length=100)),
                ('Cumulative_rf', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
