# Generated by Django 4.2.13 on 2024-07-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_lasso_predicted_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lasso_Predicted_Return',
        ),
    ]
