# Generated by Django 4.2.13 on 2024-07-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_lasso_predicted_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Predicted_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Stock', models.CharField(max_length=100)),
                ('Predicted_Return', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rd_Predicted_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Stock', models.CharField(max_length=100)),
                ('Predicted_Return', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Real_Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Stock', models.CharField(max_length=100)),
                ('Ex_Return', models.FloatField(max_length=100)),
            ],
        ),
    ]
