# Generated by Django 4.2.13 on 2024-07-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_en_predicted_return_rd_predicted_return_real_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lasso_Predicted_Return',
        ),
    ]
